### ISSUE TITLE
Falsehoods programmers believe about addresses

### ISSUE THREAD

**Issue by kurtseifried** [mr-mig/every-programmer-should-know#12]
You may have forgot:

https://www.mjt.me.uk/posts/falsehoods-programmers-believe-about-addresses/

**Comment by mr-mig** [comment]
Make a PR, I'll merge it

**Comment by mr-mig** [comment]
PR is made here: https://github.com/mr-mig/every-programmer-should-know/pull/13

**Comment by mr-mig** [comment]
Merged!
