### ISSUE TITLE
Phonenumbers are incorrectly categorized under numbers

### ISSUE THREAD

**Issue by RobThree** [mr-mig/every-programmer-should-know#18]
> ## Numbers
> 
> * [Falsehoods Programmers Believe About Phone Numbers](https://github.com/googlei18n/libphonenumber/blob/master/FALSEHOODS.md)

Phonenumbers are *not* numbers (see the referenced link):

> ## Falsehoods Programmers Believe About Phone Numbers
> ...
> **17. Phone numbers contain only digits**
> In Israel, certain advertising numbers start with a *. In New Zealand, non-urgent traffic incidents can be reported by calling *555 from a mobile phone.
> **24. Phone numbers are numbers**
> Never try to store phone numbers as an int or any other kind of numeric data type. You can't do arithmetic on them, and while 007, 07 and 7 are the same number they are not necessarily the same phone number - in some countries a leading 0 is significant and forms part of the number itself (see A leading zero in numbers formatted for domestic usage can always be discarded when dialing from abroad). Moreover, a phone number may contain other diallable characters (see Phone numbers contain only digits) or an extension portion, dialled after waiting for a tone.

Also, not mentioned in the above link, a phonenumber like `1-800 PIZZA` (name dialing / phoneword) is [valid](https://en.wikipedia.org/wiki/Phoneword) (translates to `1-800 74992`)

**Comment by mr-mig** [comment]
I'd argue that most would expect it to be in *Numbers* section. So that later they can learn the scary Truth™ :)

**Comment by RobThree** [comment]
Meh. Let's agree to disagree then 😘
