### ISSUE TITLE
Make a self-contained Repo 

### ISSUE THREAD

**Issue by eamanu** [mr-mig/every-programmer-should-know#25]
Hello @mr-mig, 

This Repo is a good idea! Congrulations!

I have  a comment, why don't we a self-conteined Repo? Without links. That mean that instead have link to external web page, we should have information inside the repo.

I could help with Spanish translation if you consider it interesting. 

Regard!

**Comment by mr-mig** [comment]
Hi @eamanu 
I think this is a great idea as well. 

However, the questions I have are:
1. What shall we do with the videos and papers? Those are only available in English mostly. 
2. What shall we do with books? Shall they have links to corresponding translated books? 
3. What benefit do you see in a self-contained repo?

**Comment by eamanu** [comment]
Hi @mr-mig 

1. There are material in Spanish. We just need found it.
2. That is a problem
3. I think that is better have all the information inside a repo and not links to external webs

**Comment by mr-mig** [comment]
I do not see much value in creating self-contained repo taking into account all related problems. 
Make it in a fork if you think it's valueable
