### ISSUE TITLE
Knowledge of implementation of Data Structures is important too

### ISSUE THREAD

**Issue by sm3saurabh** [mr-mig/every-programmer-should-know#26]
As important thing for programmers to learn is how the data structures used and implemented in the system. 
I do want to know why did you leave it from your list? If you have already added them then please inform me where did i missed it

**Comment by mr-mig** [comment]
Several people have already asked me this question, but not publicly. 
The repo is missing a good resource on data structures simply because I am not aware of anything really good.
If you have suggestions - feel free to add a new section as a PR!

**Comment by Guilhermeslucas** [comment]
I know some resources about it! I'll open a pull request!
