### ISSUE TITLE
Add a link to the "System Design: A Primer" repository

### ISSUE THREAD

**Issue by aalhour** [mr-mig/every-programmer-should-know#39]
Hi there,

I think that the [System Design: A Primer](https://github.com/donnemartin/system-design-primer) repository is really cool and I think it's a nice addition to your list.

Cheers,
Ahmad

**Comment by mr-mig** [comment]
Amazing! 👍 
Would you make a PR to the repo? 🙏

**Comment by aalhour** [comment]
Sure!

**Comment by aalhour** [comment]
Done. PR: https://github.com/mr-mig/every-programmer-should-know/pull/53
