### ISSUE TITLE
Character Sets and Encoding

### ISSUE THREAD

**Issue by jar349** [mr-mig/every-programmer-should-know#59]
Suggest adding an internationalization / text section that includes at least this:

https://www.joelonsoftware.com/2003/10/08/the-absolute-minimum-every-software-developer-absolutely-positively-must-know-about-unicode-and-character-sets-no-excuses/

**Comment by mr-mig** [comment]
It's already there under *Strings* section. Called " Unicode and Character Sets", just a shorter version of that link
